/**
 * Scribe Agent — synthesises all pipeline results into structured incident
 * documentation: postmortem, PR description, and Slack summary.
 *
 * Phase 4 responsibility:
 *   PipelineState (all agent results) → ScribeResult
 *
 * The Scribe does NOT claim resolution, test passage, or deployment
 * unless those events have actually been confirmed by earlier agents.
 */

import * as fs from 'fs';
import * as path from 'path';
import {
  IncidentPayload,
  TriageResult,
  DiagnosticResult,
  TreatmentResult,
  VerificationResult,
  ScribeResult,
} from '@shared/types';
import { AGENT_NAMES, RELATIVE_PATHS } from '@shared/constants';

// ---------------------------------------------------------------------------
// Repo-root resolver
// ---------------------------------------------------------------------------

function resolveRepoRoot(): string {
  let dir = __dirname;
  for (let i = 0; i < 10; i++) {
    if (fs.existsSync(path.join(dir, 'package.json'))) return dir;
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return process.cwd();
}

// ---------------------------------------------------------------------------
// Safe string helpers
// ---------------------------------------------------------------------------

function safe(value: string | number | boolean | undefined | null, fallback = 'N/A'): string {
  if (value === null || value === undefined) return fallback;
  return String(value);
}

function safeNum(value: number | undefined | null, fallback = 0): number {
  return (value !== null && value !== undefined) ? value : fallback;
}

function isoToReadable(iso: string | undefined): string {
  if (!iso) return 'N/A';
  try {
    return new Date(iso).toUTCString();
  } catch {
    return iso;
  }
}

// ---------------------------------------------------------------------------
// Postmortem markdown builder
// ---------------------------------------------------------------------------

function buildPostmortem(
  incident: IncidentPayload,
  triage: TriageResult,
  diagnostic: DiagnosticResult,
  treatment: TreatmentResult,
  verification: VerificationResult
): string {
  const isResolved   = verification.patchApplied && verification.regressionTestPassed;
  const isBlocked    = verification.summary.includes('BLOCKED BY MEMBER A');
  const resolution   = isResolved ? '✅ RESOLVED' : isBlocked ? '⏳ BLOCKED — PENDING MEMBER A' : '❌ UNRESOLVED';
  const rollbackNote = !verification.patchApplied && !isBlocked
    ? '\n> **Note**: The patch was rolled back because verification tests did not pass.\n'
    : '';

  return `# Incident Postmortem — ${safe(incident.incidentId)}

> Generated by REGEN Scribe Agent at ${isoToReadable(new Date().toISOString())}

---

## 1. Incident Summary

| Field | Value |
|---|---|
| **Incident ID** | ${safe(incident.incidentId)} |
| **Timestamp** | ${isoToReadable(incident.timestamp)} |
| **Service** | ${safe(incident.serviceName)} |
| **Environment** | ${safe(incident.environment)} |
| **Severity** | ${safe(incident.severity)} |
| **Endpoint** | \`${safe(incident.endpoint)}\` |
| **HTTP Status** | ${safe(incident.httpStatus)} |
| **Error Signature** | \`${safe(incident.errorSignature)}\` |
| **Resolution Status** | ${resolution} |

### Error Message

> ${safe(incident.errorMessage)}

### Impact Metrics

| Metric | Value |
|---|---|
| Error rate | ${(safeNum(incident.metrics?.errorRate) * 100).toFixed(1)}% |
| Affected users | ${safeNum(incident.metrics?.affectedUsersPercent)}% |
| P99 latency | ${safeNum(incident.metrics?.p99LatencyMs)} ms |
| Total requests | ${safeNum(incident.metrics?.totalRequests)} |
| Failed requests | ${safeNum(incident.metrics?.failedRequests)} |

---

## 2. Root Cause Analysis (Triage)

| Field | Value |
|---|---|
| **Root cause file** | \`${safe(triage.rootCauseFile)}\` |
| **Suspect function** | \`${safe(triage.suspectFunction)}()\` |
| **Line range** | ${safe(triage.lineStart)}–${safe(triage.lineEnd)} |
| **Blast radius score** | ${safeNum(triage.blastRadiusScore).toFixed(2)} / 1.0 |

### Triage Explanation

${safe(triage.explanation)}

---

## 3. Diagnostic — Reproduction

| Field | Value |
|---|---|
| **Regression test** | \`${safe(diagnostic.regressionTestPath)}\` |
| **Reproduction command** | \`${safe(diagnostic.reproductionCommand)}\` |
| **Reproduction confirmed** | ${safe(diagnostic.reproductionConfirmed)} |

The Diagnostic Agent produced a failing regression test that exercises the seeded defect
deterministically. See the test file for the full reproduction scenario.

---

## 4. Treatment — Proposed Patch

| Field | Value |
|---|---|
| **Target file** | \`${safe(treatment.targetFile)}\` |
| **Confidence score** | ${safeNum(treatment.confidenceScore).toFixed(2)} / 1.0 |
| **Blast radius factor** | ${safeNum(treatment.scoreBreakdown?.blastRadiusScore).toFixed(2)} |
| **Test specificity factor** | ${safeNum(treatment.scoreBreakdown?.testSpecificityScore).toFixed(2)} |
| **Historical success factor** | ${safeNum(treatment.scoreBreakdown?.historicalSuccessScore).toFixed(2)} |

### Patch Explanation

${safe(treatment.explanation)}

### Unified Diff

\`\`\`diff
${safe(treatment.gitDiff)}
\`\`\`

---

## 5. Verification Results
${rollbackNote}
| Field | Value |
|---|---|
| **Patch applied** | ${safe(verification.patchApplied)} |
| **Regression test passed** | ${safe(verification.regressionTestPassed)} |
| **Baseline tests passed** | ${safe(verification.baselineUnitTestsPassed)} |
| **Total tests** | ${safeNum(verification.totalTests)} |
| **Passed tests** | ${safeNum(verification.passedTests)} |
| **Failed tests** | ${safeNum(verification.failedTests)} |

### Suite Output

\`\`\`
${safe(verification.suiteOutput)}
\`\`\`

---

## 6. Timeline

| Time | Event |
|---|---|
| ${isoToReadable(incident.timestamp)} | Incident detected |
| ${isoToReadable(triage.startedAt)} | Triage started |
| ${isoToReadable(triage.completedAt)} | Triage completed (${safeNum(triage.durationMs)} ms) |
| ${isoToReadable(diagnostic.startedAt)} | Diagnostic started |
| ${isoToReadable(diagnostic.completedAt)} | Diagnostic completed (${safeNum(diagnostic.durationMs)} ms) |
| ${isoToReadable(treatment.startedAt)} | Treatment started |
| ${isoToReadable(treatment.completedAt)} | Treatment completed (${safeNum(treatment.durationMs)} ms) |
| ${isoToReadable(verification.startedAt)} | Verification started |
| ${isoToReadable(verification.completedAt)} | Verification completed (${safeNum(verification.durationMs)} ms) |

---

## 7. Follow-Up Actions

${isResolved
  ? `- [ ] Review and merge the automated fix PR.\n- [ ] Monitor error rate for 24 hours post-deployment.\n- [ ] Add DISCOUNT_PRECISION_ERROR to the immune memory store for future fast-path recovery.`
  : isBlocked
  ? `- [ ] **Member A**: Implement \`demo_service/src/services/cart.ts\` so the Treatment patch can be applied and verified.\n- [ ] Re-run the REGEN pipeline once the demo service is operational.\n- [ ] Validate the regression test passes after the cart service is implemented.`
  : `- [ ] Investigate why verification failed (see suite output above).\n- [ ] Fix the Treatment agent or re-run the full pipeline.\n- [ ] Do NOT deploy the rolled-back patch.`
}

---

## 8. Prevention

- **Root cause**: The discount precision bug results from using \`Math.trunc()\` instead of \`Math.round()\` for voucher currency conversion.
- **Fix**: A one-token substitution: \`Math.trunc\` → \`Math.round\` in \`${safe(triage.suspectFunction)}()\`.
- **Future prevention**: After verification succeeds, add this error signature to the immune memory store so subsequent occurrences are resolved in under 2 seconds via the warm path.

---

*This postmortem was automatically generated by the REGEN self-healing pipeline.*
`;
}

// ---------------------------------------------------------------------------
// PR body builder
// ---------------------------------------------------------------------------

function buildPrBody(
  incident: IncidentPayload,
  triage: TriageResult,
  diagnostic: DiagnosticResult,
  treatment: TreatmentResult,
  verification: VerificationResult
): string {
  const isResolved = verification.patchApplied && verification.regressionTestPassed;
  const isBlocked  = verification.summary.includes('BLOCKED BY MEMBER A');
  const statusBadge = isResolved ? '✅ Verified' : isBlocked ? '⏳ Pending Member A' : '❌ Verification Failed';

  return `## Summary

**Status**: ${statusBadge}
**Incident**: \`${safe(incident.incidentId)}\` — ${safe(incident.errorSignature)}
**Service**: ${safe(incident.serviceName)} (${safe(incident.environment)})
**Severity**: ${safe(incident.severity)}

---

## Problem

**Endpoint** \`${safe(incident.endpoint)}\` was returning HTTP ${safe(incident.httpStatus)} for
${safeNum(incident.metrics?.affectedUsersPercent)}% of users with a
${(safeNum(incident.metrics?.errorRate) * 100).toFixed(0)}% error rate.

Error: _${safe(incident.errorMessage)}_

---

## Root Cause

| | |
|---|---|
| File | \`${safe(triage.rootCauseFile)}\` |
| Function | \`${safe(triage.suspectFunction)}()\` |
| Lines | ${safe(triage.lineStart)}–${safe(triage.lineEnd)} |
| Blast radius | ${safeNum(triage.blastRadiusScore).toFixed(2)} |

${safe(triage.explanation)}

---

## Reproduction

Regression test: \`${safe(diagnostic.regressionTestPath)}\`

The test asserts \`convertVoucherDiscount(10, 'EUR', 'USD') === 11\` (rounded), but the
buggy code returns \`10\` (truncated). Run with: \`${safe(diagnostic.reproductionCommand)}\`

---

## Treatment

**Confidence score**: ${safeNum(treatment.confidenceScore).toFixed(2)} / 1.0

\`\`\`diff
${safe(treatment.gitDiff)}
\`\`\`

---

## Verification

| Test category | Result |
|---|---|
| Regression test | ${verification.regressionTestPassed ? '✅ PASS' : '❌ FAIL / NOT RUN'} |
| Baseline unit tests | ${verification.baselineUnitTestsPassed ? '✅ PASS' : '❌ FAIL / NOT RUN'} |
| Patch applied | ${verification.patchApplied ? '✅ YES' : '❌ NO'} |

${isBlocked ? '> ⚠️ Verification is BLOCKED pending Member A implementing the demo service.' : ''}
${!isResolved && !isBlocked ? '> ⚠️ Verification failed. The patch has been rolled back. Do not merge.' : ''}

---

*Auto-generated by REGEN self-healing pipeline.*
`;
}

// ---------------------------------------------------------------------------
// PR title builder
// ---------------------------------------------------------------------------

function buildPrTitle(
  incident: IncidentPayload,
  triage: TriageResult,
  verification: VerificationResult
): string {
  const isResolved = verification.patchApplied && verification.regressionTestPassed;
  const prefix     = isResolved ? 'fix' : 'fix(pending)';
  const scope      = triage.rootCauseFile.split('/').pop()?.replace('.ts', '') ?? 'cart';
  return `${prefix}(${scope}): replace Math.trunc with Math.round in ${triage.suspectFunction}() [${safe(incident.incidentId)}]`;
}

// ---------------------------------------------------------------------------
// Slack notification builder
// ---------------------------------------------------------------------------

function buildSlackNotification(
  incident: IncidentPayload,
  triage: TriageResult,
  treatment: TreatmentResult,
  verification: VerificationResult
): string {
  const isResolved = verification.patchApplied && verification.regressionTestPassed;
  const isBlocked  = verification.summary.includes('BLOCKED BY MEMBER A');

  const statusIcon  = isResolved ? '✅' : isBlocked ? '⏳' : '❌';
  const statusText  = isResolved ? 'AUTO-RESOLVED' : isBlocked ? 'PENDING (blocked on demo service)' : 'UNRESOLVED — patch rolled back';

  return [
    `${statusIcon} *REGEN Self-Healing Pipeline — Incident Update*`,
    ``,
    `*Incident*: \`${safe(incident.incidentId)}\` | ${safe(incident.severity)} | ${safe(incident.serviceName)}`,
    `*Endpoint*: \`${safe(incident.endpoint)}\` → HTTP ${safe(incident.httpStatus)}`,
    `*Impact*: ${safeNum(incident.metrics?.affectedUsersPercent)}% users affected, ${(safeNum(incident.metrics?.errorRate) * 100).toFixed(0)}% error rate`,
    ``,
    `*Root cause*: \`${safe(triage.suspectFunction)}()\` in \`${safe(triage.rootCauseFile)}\``,
    `> ${safe(triage.explanation).split('\n')[0].replace(/\*\*/g, '')}`,
    ``,
    `*Treatment*: \`Math.trunc\` → \`Math.round\` (confidence: ${safeNum(treatment.confidenceScore).toFixed(2)})`,
    `*Regression test*: ${verification.regressionTestPassed ? '✅ PASS' : '❌ FAIL / NOT RUN'}`,
    `*Baseline tests*: ${verification.baselineUnitTestsPassed ? '✅ PASS' : '❌ FAIL / NOT RUN'}`,
    ``,
    `*Status*: ${statusText}`,
    isBlocked ? `_Waiting for Member A to implement demo_service — re-run pipeline once complete._` : '',
  ].filter(l => l !== '').join('\n');
}

// ---------------------------------------------------------------------------
// Postmortem file writer (optional, best-effort)
// ---------------------------------------------------------------------------

function writePostmortemFile(
  repoRoot: string,
  incidentId: string,
  markdown: string
): string {
  const dir     = path.join(repoRoot, RELATIVE_PATHS.GENERATED_POSTMORTEMS);
  const safeId  = incidentId.replace(/[^a-zA-Z0-9-_]/g, '-');
  const relPath = `${RELATIVE_PATHS.GENERATED_POSTMORTEMS}/${safeId}.md`;
  try {
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(repoRoot, relPath), markdown, 'utf8');
  } catch {
    // Non-fatal — postmortem is still returned in the result
  }
  return relPath;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export class ScribeAgent {
  /**
   * Generates all Scribe outputs from the completed pipeline context.
   *
   * All four required ScribeResult fields are always populated.
   * The postmortem accurately reflects whether verification succeeded or was blocked.
   */
  public async run(
    incident: IncidentPayload,
    triage: TriageResult,
    diagnostic: DiagnosticResult,
    treatment: TreatmentResult,
    verification: VerificationResult
  ): Promise<ScribeResult> {
    const startedAt = new Date().toISOString();
    const repoRoot  = resolveRepoRoot();

    let status: 'success' | 'failed' = 'success';
    let errorMsg: string | undefined;

    let postmortemMarkdown = '';
    let prTitle            = '';
    let prBody             = '';
    let slackText          = '';
    let postmortemFilePath = '';

    try {
      postmortemMarkdown = buildPostmortem(incident, triage, diagnostic, treatment, verification);
      prTitle            = buildPrTitle(incident, triage, verification);
      prBody             = buildPrBody(incident, triage, diagnostic, treatment, verification);
      slackText          = buildSlackNotification(incident, triage, treatment, verification);
      postmortemFilePath = writePostmortemFile(repoRoot, incident.incidentId, postmortemMarkdown);
    } catch (err: unknown) {
      status   = 'failed';
      errorMsg = err instanceof Error ? err.message : 'Unknown scribe error';
    }

    const completedAt = new Date().toISOString();
    const durationMs  = new Date(completedAt).getTime() - new Date(startedAt).getTime();

    return {
      agentName:             AGENT_NAMES.SCRIBE,
      status,
      startedAt,
      completedAt,
      durationMs,
      summary:
        status === 'success'
          ? `Scribe completed: postmortem, PR, and Slack summary generated for ${incident.incidentId}`
          : `Scribe failed: ${errorMsg}`,
      postmortemMarkdown,
      prTitle,
      prBody,
      slackNotificationText: slackText,
      postmortemFilePath,
      ...(errorMsg ? { error: errorMsg } : {}),
    };
  }
}
